#!/bin/sh


# quit the soundcard app
osascript -e 'tell app "ohSoundcard" to quit'

# unload the driver
kextunload /System/Library/Extensions/ohSoundcard.kext
if [ $? != 0 ]; then
    kextunload /System/Library/Extensions/ohSoundcard.kext
fi

exit 0

